name: Build

on:
  push:
    branches: [ "master" ]  # Use "main" instead of "master" for consistency
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Use the latest version of actions/checkout

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Build release app bundle
        run: flutter build appbundle


      - name: Sign App Bundle
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: build/app/outputs/bundle/release/
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_FILE_BASE64 }}
          alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}

#      # Add steps to build the Android app here, e.g.,
#      - name: Build Android APK
#        run: flutter build apk
